name: Checker

on: 
  push:
  workflow_dispatch:

jobs:
  checker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/robertgrancsa/sd-tema-3:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          hw_checker --legacy